judge works better as a function than as a script

diff --git a/zsh/aliases b/zsh/aliases
--- a/zsh/aliases
+++ b/zsh/aliases
@@ -13,6 +13,8 @@ alias ls="ls -FG"
 alias plainls="unalias ls" # Temporarily remove the alias above
 alias ll="ls -lAh"
 
+alias .f="cd ~/.dotfiles"
+
 # commands starting with % for pasting from web
 alias %=' '
 
@@ -54,7 +56,35 @@ function diagnose() { sudo dtruss -cade -p "$1" 2>&1 | tee /tmp/ruby_diagnosis }
 # Define a word
 function define() { curl dict://dict.org/d:$1 }
 
-# Recursively grep in files
+# Recursively find in files
 function grepfiles(){ grep -Ri $1 *}
 
-alias work='cd ~/work; mvim -p billable_hours.csv general_todo.md poms.md sharpening.md slowness.md team_dynamics.md'
+alias work='cd ~/work; vim -p billable_hours.csv general_todo.md poms.md sharpening.md slowness.md team_dynamics.md'
+
+# Usage:
+# - with args, `judge rspec spec`; runs yay or boom depending on exit status of given command
+# - without args, `rspec spec; judge`; runs yay or boom depending on exit status of previous command
+function judge() {
+  last_exit_status=$?
+  number_of_args=$#
+  if [ $number_of_args -gt 0 ]
+  then
+    # - treat the args as a command to run
+    # - $@ is all the args given
+    # - `"$@"` makes sure that quoting is preserved - eg, if the command was
+    #    `judge echo one "two three"` we'll have two args, not three
+    # - Once the expansion is done, the shell sees a bare command and runs it. If
+    #   we'd put `echo "$@"` instead, that might expand to `echo rspec spec`, so it
+    #   would run `echo` and pass in the arguments `rspec` and `spec`
+    "$@" && yay || boom
+  else
+    # No args given means no command to run, so check the exit status of the
+    # last command and notify accordingly
+    if [ $last_exit_status -eq 0 ]
+    then
+      yay
+    else
+      boom
+    fi
+  fi
+}
